split architecture lib/utils
ipdk-io/ptf-tests pull request #2
Opened 2022-11-18 23:06 UTC by sjwahub

Signed-off-by: Shujun Wang <shujun.wang@intel.com>

Initial draft  

unit test log: 
[SplitArcUnitTestCase.txt](https://github.com/ipdk-io/ptf-tests/files/10045405/SplitArcUnitTestCase.txt)

2022-12-06 03:36 UTC, stadju approved these changes

2022-12-06 03:38 UTC, dkaranjai requested changes
General Comment: Please add comments to all test case steps

2022-12-07 03:47 UTC, dkaranjai commented
Brief of changes: 

 

Lib changes 

 1.1   New files "p4rt_ctl.py" and "p4rt-ctl.in" are introduced  

 1.2   "port_config.py" is modified by changing all "gnmi_cli" to 'gnmi_ctl' 

 1.3   Feature specific changes  

 

Utils changes 

2.1   "gnmi_ctl_utils.py" is to replace "gnmi_cli.utils.py" 

2.2    "p4rtctl_utils.py" is to replace "ovsp4ctl_utils.py" 

2.3    new utils "log.py" is introduced with timestamp  

2.4    Delete old "p4ovs_utils.py" and "gnmi_cli_utils.py" 

2.5    Feature specific changes  

 

Test Cases changes 

3.1  import statement need changes 

3.2  All p4ovs-ctl and gnmi_cli need to be replaced  in all test cases with p4rt_ctl and gnmi_ctl respectively  

3.3  All  print() for logging purpose, except for usage purpose, should be replaced by log.passed(), log.info(), log.failed() and log.warning() accordingly 

3.4  There are total 66 test cases in https://github.com/ipdk-io/ptf-tests.  [ Additional 6 ECMP FRR case need to be moved to this location ] 

In which, 31 test cases need to call new utils "test_utils.gen_dep_files_p4c_tdi_pipeline_builder()" instead of old "test_utils.gen_dep_files_p4c_ovs_pipeline_builder()" 

For remaining test cases, old function name "gen_dep_files_p4c_dpdk_pna_ovs_pipeline_builder()" with new code is still being used. We need to rename it to  "gen_dep_files_p4c_dpdk_pna_tdi_pipeline_builder()" 

 

3.5  All test cases are impacted by following utils functions (previously p4ovs_ctl, now p4rt_ctl) 

 add-entry SWITCH TABLE FLOW           adds new table entry 

 del-entry SWITCH TABLE KEY                 deletes table entry with KEY from TABLE 

 dump-entries SWITCH [TBL]                   prints table entries 

 set-default-entry SWITCH TBL ACTION       sets default table entry for TBL 

 get-default-entry SWITCH TBL          prints default table entry for TBL 

 add-action-profile-member SWITCH PROFILE FLOW      adds member reference 

 delete-action-profile-member SWITCH PROFILE FLOW      deletes member reference 

 get-action-profile-member SWITCH PROFILE FLOW      prints member entries 

 add-action-profile-group SWITCH PROFILE FLOW      adds group reference 

 delete-action-profile-group SWITCH PROFILE FLOW      deletes group reference 

 get-action-profile-group SWITCH PROFILE FLOW      prints group entries 

 get-counter SWITCH CTR_TBL CTR_FLOW       gets indirect counter table entry 

 reset-counter SWITCH CTR_TBL CTR_FLOW     resets counter table entry 

 

3.6 All test case formatting related changes 

Documentation 

Python Typing  

Python Lint -- Black

2022-12-08 03:23 UTC, stadju approved these changes

2022-12-09 04:11 UTC, dkaranjai requested changes
Also please check the comments once. noticed a few discrepencies:
1. no space after "#"
2. spelling mistakes like "2th"

2022-12-09 04:11 UTC, dkaranjai commented on tests/DPDK_Hot_Plug_multi_port_test.py
> +        # Compile p4 file using p4c compiler and generate binary using ovs pipeline builder
will this be ovs or tdi ?

2022-12-09 04:11 UTC, dkaranjai commented on tests/dpdk_l3em_indirect_counter.py
>              self.fail("Failed to configure gnmi cli ports")
ctl

2022-12-09 04:11 UTC, dkaranjai commented on tests/l2_exact_match_with_tap_port.py
>              self.fail("Failed to configure gnmi cli ports")
ctl

2022-12-09 04:11 UTC, dkaranjai commented on tests/l3_exact_match_with_vhost_add_del.py
>              self.fail("Failed to configure gnmi cli ports")
ctl

2022-12-09 04:11 UTC, dkaranjai commented on tests/lnt_4vm_on_same_host.py
>              self.fail("Failed to configure gnmi cli ports")
ctl

2022-12-09 04:11 UTC, dkaranjai commented on tests/l2_dpdk_port_flapping_with_tap_ports.py
> +
reference to gnmi-cli in multple places

2022-12-09 04:11 UTC, dkaranjai commented on tests/l2_dpdk_port_flapping_with_tap_ports.py
>          :return: None
p4ovs pipeline?

2022-12-09 04:11 UTC, dkaranjai commented on tests/l2_exact_match_with_tap_port.py
>          self.gnmicli_params = get_gnmi_params_simple(self.config_data)
gnmictl

2022-12-09 04:11 UTC, dkaranjai commented on tests/l2_exact_match_with_tap_port.py
> +        if not gnmi_ctl_set_and_verify(self.gnmicli_params):
gnmictl

2022-12-09 04:11 UTC, dkaranjai commented on tests/l2_exact_match_with_tap_port.py
>              self.fail("Failed to configure gnmi cli ports")
gnmictl

2022-12-09 04:11 UTC, dkaranjai commented on tests/l3_action_profile_with_link_ports.py
> +        # Compile p4 file using p4c compiler and generate binary using ovs pipeline builder
ovs or tdi

2022-12-09 04:11 UTC, dkaranjai commented on tests/l3_action_profile_with_tap_ports.py
>              self.fail("Failed to configure gnmi cli ports")
ctl

2022-12-09 04:11 UTC, dkaranjai commented on tests/l3_action_selector_with_tap_ports.py
>              self.fail("Failed to configure gnmi cli ports")
ctl

2022-12-09 04:11 UTC, dkaranjai commented on tests/l3_dpdk_port_flapping_with_vhost_ports.py
>          :rtype: None
p4ovs pipeline?

2022-12-09 04:11 UTC, dkaranjai commented on tests/l3_exact_match_with_tap_port.py
> +        # Compile p4 file using p4c compiler and generate binary using ovs pipeline builder
ovs pipeline builder? or tdi?

2022-12-09 04:11 UTC, dkaranjai commented on tests/l3_exact_match_with_vhost_add_del.py
> +        if not gnmi_ctl_set_and_verify(self.gnmicli_params):
ctl

2022-12-09 04:11 UTC, dkaranjai commented on tests/l3_exact_match_with_vhost_add_del.py
>  class L3_Exact_Match(BaseTest):
self.gnmicli_params = get_gnmi_params_simple(self.config_data)
need to change this

2022-12-09 04:11 UTC, dkaranjai commented on tests/l3_wcm_with_tap_ports.py
> +        # Compile p4 file using p4c compiler and generate binary using ovs pipeline builder
ovs pipeline builder?

2022-12-09 04:11 UTC, dkaranjai commented on tests/lnt_1hotplugvm_vxlan_1nsvm.py
>              self.fail("Failed to configure hotplug through gnmi")
ctl

2022-12-09 04:11 UTC, dkaranjai commented on tests/lnt_2hotplugvm_vxlan_2nsvm.py
>              self.fail("Failed to configure gnmi cli ports")
ctl

2022-12-09 04:11 UTC, dkaranjai commented on tests/lnt_2hotplugvm_vxlan_2nsvm.py
>          # Configure P4OVS, VM, VLAN adn VXLAN on Local Host #
P4OVS?

2022-12-09 04:11 UTC, dkaranjai commented on tests/lnt_2vm_vxlan_2nsvm_5min_ping.py
>          self.gnmicli_params = get_gnmi_params_simple(self.config_data)
gnmictl

2022-12-09 04:11 UTC, dkaranjai commented on tests/lnt_2vm_vxlan_2nsvm_5min_ping.py
>          self.gnmicli_hotplug_params = get_gnmi_params_hotplug(self.config_data)
gnmictl

2022-12-09 04:11 UTC, dkaranjai commented on tests/lnt_4vm_2host_add_dele_rule.py
>          self.gnmicli_params = get_gnmi_params_simple(self.config_data)
ctl

2022-12-09 04:11 UTC, dkaranjai commented on tests/lnt_4vm_2host_add_dele_rule.py
> +        if not gnmi_ctl_utils.gnmi_ctl_set_and_verify(self.gnmicli_params):
gnmicli_params -> gnmictl

2022-12-09 04:11 UTC, dkaranjai commented on tests/lnt_4vm_on_same_host.py
>          self.gnmicli_params = get_gnmi_params_simple(self.config_data)
gnmictl

2022-12-09 04:11 UTC, dkaranjai commented on tests/lnt_4vm_on_same_host.py
> +        if not gnmi_ctl_set_and_verify(self.gnmicli_params):
gnmictl

2022-12-09 04:15 UTC, stadju approved these changes

2022-12-09 04:29 UTC, sjwahub commented on tests/l2_exact_match_with_tap_port.py
>              self.fail("Failed to configure gnmi cli ports")
resolved

2022-12-09 04:32 UTC, sjwahub commented on tests/dpdk_l3em_indirect_counter.py
>              self.fail("Failed to configure gnmi cli ports")
resolved

2022-12-09 04:38 UTC, sjwahub commented on tests/lnt_2vm_vxlan_2nsvm_5min_ping.py
>          self.gnmicli_hotplug_params = get_gnmi_params_hotplug(self.config_data)
fixed

2022-12-09 04:39 UTC, sjwahub commented on tests/lnt_4vm_2host_add_dele_rule.py
>          self.gnmicli_params = get_gnmi_params_simple(self.config_data)
fixed

2022-12-09 04:41 UTC, sjwahub commented on tests/DPDK_Hot_Plug_multi_port_test.py
> +        # Compile p4 file using p4c compiler and generate binary using ovs pipeline builder
This is a merge issue. At my end, it looks good

2022-12-09 04:44 UTC, sjwahub commented on tests/l3_exact_match_with_vhost_add_del.py
>              self.fail("Failed to configure gnmi cli ports")
fixed

2022-12-09 04:45 UTC, sjwahub commented on tests/lnt_4vm_2host_add_dele_rule.py
> +        if not gnmi_ctl_utils.gnmi_ctl_set_and_verify(self.gnmicli_params):
fixed

2022-12-09 04:47 UTC, sjwahub commented on tests/lnt_4vm_on_same_host.py
>          self.gnmicli_params = get_gnmi_params_simple(self.config_data)
fixed

2022-12-09 04:48 UTC, sjwahub commented on tests/lnt_4vm_on_same_host.py
> +        if not gnmi_ctl_set_and_verify(self.gnmicli_params):
fixed

2022-12-09 04:50 UTC, sjwahub commented on tests/l2_dpdk_port_flapping_with_tap_ports.py
> +
fixed

2022-12-09 04:52 UTC, sjwahub commented on tests/l2_dpdk_port_flapping_with_tap_ports.py
>          :return: None
fixed

2022-12-09 04:53 UTC, sjwahub commented on tests/l2_exact_match_with_tap_port.py
>          self.gnmicli_params = get_gnmi_params_simple(self.config_data)
fixed

2022-12-09 04:53 UTC, sjwahub commented on tests/l2_exact_match_with_tap_port.py
>              self.fail("Failed to configure gnmi cli ports")
fixed

2022-12-09 04:55 UTC, sjwahub commented on tests/l3_action_profile_with_link_ports.py
> +        # Compile p4 file using p4c compiler and generate binary using ovs pipeline builder
merge issue ? No issue at my end

2022-12-09 04:58 UTC, sjwahub commented on tests/l3_action_profile_with_tap_ports.py
>              self.fail("Failed to configure gnmi cli ports")
fixed

2022-12-09 04:59 UTC, sjwahub commented on tests/l2_exact_match_with_tap_port.py
> +        if not gnmi_ctl_set_and_verify(self.gnmicli_params):
fixed

2022-12-09 05:03 UTC, sjwahub commented on tests/l3_action_selector_with_tap_ports.py
>              self.fail("Failed to configure gnmi cli ports")
fixed

2022-12-09 05:05 UTC, sjwahub commented on tests/l3_dpdk_port_flapping_with_vhost_ports.py
>          :rtype: None
fixed

2022-12-09 05:07 UTC, sjwahub commented on tests/l3_exact_match_with_tap_port.py
> +        # Compile p4 file using p4c compiler and generate binary using ovs pipeline builder
fixed

2022-12-09 05:08 UTC, sjwahub commented on tests/l3_exact_match_with_vhost_add_del.py
> +        if not gnmi_ctl_set_and_verify(self.gnmicli_params):
fixed

2022-12-09 05:09 UTC, sjwahub commented on tests/l3_exact_match_with_vhost_add_del.py
>  class L3_Exact_Match(BaseTest):
changed

2022-12-09 05:10 UTC, sjwahub commented on tests/l3_wcm_with_tap_ports.py
> +        # Compile p4 file using p4c compiler and generate binary using ovs pipeline builder
fixed

2022-12-09 05:11 UTC, sjwahub commented on tests/lnt_1hotplugvm_vxlan_1nsvm.py
>              self.fail("Failed to configure hotplug through gnmi")
fixed

2022-12-09 05:13 UTC, sjwahub commented on tests/lnt_2hotplugvm_vxlan_2nsvm.py
>              self.fail("Failed to configure gnmi cli ports")
fxied

2022-12-09 05:15 UTC, sjwahub commented on tests/lnt_2hotplugvm_vxlan_2nsvm.py
>          # Configure P4OVS, VM, VLAN adn VXLAN on Local Host #
fixed

2022-12-09 06:37 UTC, sjwahub commented on tests/DPDK_Hot_Plug_multi_port_test.py
> +        # Compile p4 file using p4c compiler and generate binary using ovs pipeline builder
clone this branch and fixed it

2022-12-09 06:39 UTC, sjwahub commented on tests/lnt_4vm_on_same_host.py
>              self.fail("Failed to configure gnmi cli ports")
fixed

2022-12-09 10:18 UTC, dkaranjai approved these changes

2022-12-13 04:07 UTC, dkaranjai commented
Changes moved to PR #3

2022-12-13 04:07 UTC, closed without merging