Adding 2 Negative Test cases
ipdk-io/ptf-tests pull request #30
Opened 2023-02-17 07:53 UTC by hirentha

2023-02-17 09:31 UTC, dkaranjai requested changes

2023-02-17 09:31 UTC, dkaranjai commented on common/lib/port_config.py
> +                raise ExecuteCMDException(f"Max+1 port created")
remove 'f'

2023-02-17 09:31 UTC, dkaranjai commented on common/utils/gnmi_ctl_utils.py
> +    port_config = PortConfig()
add function description

2023-02-17 09:31 UTC, dkaranjai commented on tests/nt_out_range_port.py
> +        check_vhost = check_and_clear_vhost(socket_path_dir)
add comment

2023-02-17 09:31 UTC, dkaranjai commented on tests/nt_send_traffic_non_existing_group.py
> +                f" Verification of udp packet check passed : No traffic from TAP3 to TAP1 port"
remove 'f'

2023-02-17 09:31 UTC, dkaranjai commented on tests/nt_send_traffic_non_existing_group.py
> +                f" Verification of udp packet check passed : No traffic from TAP3 to TAP2 port"
removed 'f'

2023-02-17 10:39 UTC, sjwahub approved these changes

2023-02-17 12:06 UTC, sjwahub commented
Unit test log?

2023-02-17 17:27 UTC, hirentha commented
[Negative_Test_Cases_Logs.txt](https://github.com/ipdk-io/ptf-tests/files/10769266/Negative_Test_Cases_Logs.txt)

2023-02-20 04:01 UTC, sjwahub approved these changes

2023-02-21 05:18 UTC, dkaranjai approved these changes

2023-02-21 05:18 UTC, merged