IPDK Negative Test Cases
ipdk-io/ptf-tests pull request #31
Opened 2023-02-21 05:43 UTC by sjwahub

Unit Test log  [ptf_tests_run_neg_final_1.log](https://github.com/ipdk-io/ptf-tests/files/10789977/ptf_tests_run_neg_final_1.log)

2023-02-21 06:09 UTC, dkaranjai requested changes

2023-02-21 06:09 UTC, dkaranjai commented on common/lib/port_config.py
> +        def gnmi_ctl_set_invalid_args(self, params):
you dont need this. this is the reverse of the existing one. the utils function is sufficient with the pass/fail checks reversed.

2023-02-21 06:09 UTC, dkaranjai commented on common/utils/gnmi_ctl_utils.py
> +def gnmi_ctl_set_and_verify_invalid_args(params):
refer to the comment on port_config.py

2023-02-21 06:09 UTC, dkaranjai commented on tests/LNT_ECMP_2VM_2Host_Invalid_Value.py
> +            self.fail("Failed to bring up {self.tap_port_list[0]}")
f missing

2023-02-21 06:09 UTC, dkaranjai commented on tests/LNT_ECMP_2VM_2Host_Invalid_Value.py
> +            self.fail(f"Failed to add route")
f not required

2023-02-21 06:09 UTC, dkaranjai commented on tests/LNT_ECMP_2VM_2Host_Invalid_Value.py
> +        log.info("Unconfiguration on remote host")
replace unconfiguration with cleanup

2023-02-21 06:09 UTC, dkaranjai commented on tests/LNT_ECMP_2VM_2Host_Negative.py
> +        log.info("Unconfiguration on remote host")
refer previous test script

2023-02-21 11:40 UTC, sjwahub commented
Unit test log for code changes based on comment [ptf_tests_run_negaive_2.log](https://github.com/ipdk-io/ptf-tests/files/10793063/ptf_tests_run_negaive_2.log)

2023-02-22 03:52 UTC, dkaranjai approved these changes

2023-02-22 03:52 UTC, merged