Split Architecture: LNT ECMP test automation cases
ipdk-io/ptf-tests pull request #5
Opened 2022-12-15 23:30 UTC by sjwahub

Signed-off-by: Shujun Wang <shujun.wang@intel.com>

1. This PR is for all LNT ECMP related test cases based split architecture
2. The unit test log 
[lnt_ecmp_unittest_log.txt](https://github.com/ipdk-io/ptf-tests/files/10241425/lnt_ecmp_unittest_log.txt)

2022-12-16 04:13 UTC, stadju approved these changes

2022-12-19 04:46 UTC, dkaranjai requested changes
Please make this change in the util/lib:

**PASS**: successfully executed "netperf -H 99.0.0.4 -l 10 -t UDP_STREAM -- -m 1000" with below output
 netperf -H 99.0.0.4 -l 10 -t UDP_STREAM -- -m 1000

2022-12-20 07:18 UTC, sjwahub commented
> Please make this change in the util/lib:
> 
> **PASS**: successfully executed "netperf -H 99.0.0.4 -l 10 -t UDP_STREAM -- -m 1000" with below output netperf -H 99.0.0.4 -l 10 -t UDP_STREAM -- -m 1000

Fix it with message as a proof

12/19/2022,22:49:25  INFO: execute netperf -H 99.0.0.2 -l 10 -t TCP_STREAM -- -m 1000 on VM0
12/19/2022,22:49:55  PASSED: send netperf -H 99.0.0.2 -l 10 -t TCP_STREAM -- -m 1000 succeed with below output

netperf -H 99.0.0.2 -l 10 -t TCP_STREAM -- -m 1000
MIGRATED TCP STREAM TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 99.0.0.2 () port 0 AF_INET : demo
Recv   Send    Send
Socket Socket  Message  Elapsed
Size   Size    Size     Time     Throughput
bytes  bytes   bytes    secs.    10^6bits/sec

131072  16384   1000    10.01    1687.78
root@TRAFFICGEN:~#

12/19/2022,22:49:55  INFO: execute netperf -H 99.0.0.3 -l 10 -t TCP_STREAM -- -m 1000 on VM0

2022-12-20 10:04 UTC, dkaranjai approved these changes

2022-12-20 10:04 UTC, merged