Test IPU performance
ipdk-io/ptf-tests pull request #56
Opened 2023-11-29 09:47 UTC by pkulax

2023-12-06 13:01 UTC, pkacprza requested changes

2023-12-06 13:01 UTC, pkacprza commented on storage/tests/system_tools/test_platform.py
> +        sudo taskset -c 32-47 fio --name=test --rw=randwrite {filenames}\
instead of "32-47" you want to have first and last element of cpus_to_use list

2023-12-06 13:01 UTC, pkacprza commented on storage/tests/system_tools/test_platform.py
> +            spdk_cpu_mask = "0xffff00000000"
each machine can have different SPDK mask, using one as a const is not recommended

2023-12-06 13:01 UTC, pkacprza commented on storage/tests/system_tools/test_platform.py
> +    def _run_second_spdk_sock(self):
you don't need to run second SPDK process

2023-12-07 12:42 UTC, pkacprza approved these changes

2023-12-12 10:46 UTC, intelfisz commented on storage/tests/system_tools/const.py
> +SPDK_VERSION = "v23.05"
OPI already uses 23.09

2023-12-13 08:54 UTC, merged